version: '3.8'
services:
    web:
        container_name: go-base-service
        build:
            context: ./
            target: dev
            dockerfile: ./docker/go/Dockerfile
        ports:
            - 8780:8080
        volumes:
            - .:/go/src/github.com/domibustosb/go_base
        env_file:
            - ./config/dev.env
    postgresql:
        image: postgres:latest
        container_name: base-postgresql
        env_file:
          - ./config/postgresql.dev.env
        ports: 
          - '5432:5432'